import fs from 'node:fs/promises';
import path from 'node:path';
import YAML from 'yaml';
import { TAXONOMY_DIR } from '../config.js';
import { CategoryTaxonomy, CategoryKey } from '../schema/index.js';

/**
 * Generates `bundled.ts` from the YAML taxonomy files, so a browser build
 * (which cannot `fs.readFile` at runtime) can import parsed taxonomy data
 * directly instead. Node/eval usage is unaffected — `loadTaxonomy` still
 * reads the YAML live so editing a taxonomy file doesn't require a rebuild;
 * this bundle is only what a shipped extension would import.
 *
 * Run via `npm run build:taxonomy` whenever a taxonomy YAML file changes.
 */

async function main(): Promise<void> {
  const files = (await fs.readdir(TAXONOMY_DIR)).filter((f) => f.endsWith('.yaml'));
  const entries: [string, CategoryTaxonomy][] = [];

  for (const file of files) {
    const category = path.basename(file, '.yaml');
    if (!CategoryKey.safeParse(category).success) {
      throw new Error(`${file}: "${category}" is not a known CategoryKey`);
    }
    const raw = await fs.readFile(path.join(TAXONOMY_DIR, file), 'utf8');
    const parsed = CategoryTaxonomy.parse(YAML.parse(raw));
    entries.push([category, parsed]);
  }
  entries.sort(([a], [b]) => a.localeCompare(b));

  const body = entries.map(([category, tax]) => `  ${category}: ${JSON.stringify(tax)},`).join('\n');

  const out = `// GENERATED by \`npm run build:taxonomy\`. Do not hand-edit — edit the
// YAML files in src/taxonomy/data/ and regenerate instead.
import type { CategoryKey, CategoryTaxonomy } from '../schema/index.js';

export const BUNDLED_TAXONOMY: Partial<Record<CategoryKey, CategoryTaxonomy>> = {
${body}
};
`;

  await fs.writeFile(path.join(path.dirname(TAXONOMY_DIR), 'bundled.ts'), out, 'utf8');
  console.log(`Wrote src/taxonomy/bundled.ts (${entries.length} categories)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
